IMG_DIR: "datasets/vg/VG_100K"
ROIDB_FILE: "datasets/vg/VG-SGG-with-attri.h5"
DICT_FILE: "datasets/vg/VG-SGG-dicts-with-attri.json"
IMAGE_FILE: "datasets/vg/image_data.json"
NEW_RELATION:
  ENABLE: True
  # other rules
  USE_KG: True  #False
  FILTER_FREQ_REL: True
  NEW_REL_FILTER: "pretrain" # ovlp/nn/none/iou/pretrain
  RANK_PAIRS: False
  N_SPO_RULE: True # number of specific triple should > 0 in trainset
  TOP_K_FREQ: 15
  SAMPLE_REL_FROM_PROB: True
  # internal transfer
  COMB_INTERNAL_TRANS: False
  INTERNAL_FILE: "datasets/vg/intrans_rel.pk"
  # KG config
  KG_DATA_ROOT: "datasets/kg/triple-prior"
  USE_CONTEXT: True
  USE_DISTILLATION: True
  # with context
  KMEANS_MODEL: "datasets/kg/context-based/kmeans_25.pkl"
  KMEANS_PRED_FILE: "datasets/kg/context-based/kmeans_25_prediction_combined_img2cluster.pkl"
  CLUSTER_TO_KNOWLEDGE: "triple_prob-context-distill-tfidf-no_new_rels-no_frequent_preds.pkl"
  # without context
  PAIR_SCORE: "subject2pair_prob.json"
  TOP_REL_OF_PAIR: "subj_obj_to_top_pred.json"
  NO_CONTEXT_TRIPLE_PROB: "triple_prob.pkl"
  # path and names
  REL_CACHE_PREFIX: "_pretrain_tfidf_N35"
  VIS_OUT_DIR: ""
  OUTPUT_DIR: ""
USE_LOGITS:
  ENABLE: True
  STAGE: "deduction"     # "get-logits", "deduction"
  COMB_METHOD: "mult"    # "mult", "sum"
  SPECIFIED_DATA_FILE: 'datasets/vg/vg_sup_data.pk'
  DATA_WITH_LOGITS: ""
  LOGITS_COMB_PRIOR: ""
